---
- name: create packages download dir
  file: path=/root/packages state=directory

- name: override OpenVPN architecture on amd64
  set_fact:
      openvpnas_arch: amd_64
  when: 'ansible_architecture == "x86_64"'

- name: download openvpnas for Debian/Ubuntu
  get_url: url={{ openvpnas_deb_url }} dest={{openvpnas_download_dir}}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: ["packages","openvpnas"]

- name: install openvpnas for Debian/Ubuntu
  command: dpkg -E -i {{ openvpnas_download_dir }}/{{ openvpnas_deb_file }}
  register: dpkg_install_result
  changed_when: "'already installed' not in dpkg_install_result.stderr"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags: ["packages","openvpnas"]

- name: configure openvpnas
  command: "{{openvpnas_base_path}}/scripts/confdba --key={{item.key}} --value={{item.value}} --prof={{openvpnas_profil}}"
  notify: restart openvpnas
  with_items: openvpnas_params 
  tags: ["configuration","openvpnas"]

- name: ensure openvpnas is started/stopped
  service: name=openvpnas state={{ openvpnas_service_state }} enabled={{ openvpnas_service_enabled }}
  tags: ["service","openvpnas"]

